# Numpy Basic

In [78]:
import numpy as np

## data type

array의 dtype을 본다. 

In [3]:
arr = np.array([[1, 2, 3], [1, 2, 3]])

In [4]:
arr.dtype

dtype('int64')

.astype()으로 datatype을 변환 가능

In [6]:
arr.astype('float32')

array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float32)

In [8]:
arr.astype(np.int32)

array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)

In [10]:
arr = np.array([[1, 2, 3], [1, 2, 3]], dtype = np.uint8 )
arr.dtype

dtype('uint8')

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [11]:
arr.shape

(2, 3)

In [12]:
len(arr.shape)

2

size 확인

In [14]:
arr.size

6

dtype 확인

In [15]:
arr.dtype

dtype('uint8')

## Reshape

In [17]:
arr.shape

(2, 3)

Reshape 

In [19]:
arr = arr.reshape([1, 6])
arr.shape

(1, 6)

In [20]:
arr.reshape([6]).shape

(6,)

Reshape, -1 활용

In [21]:
arr.reshape(-1)  # 마지막차원에서 사이즈에서 남는것 차원으로 들어감

array([1, 2, 3, 1, 2, 3], dtype=uint8)

In [22]:
arr = arr.reshape(-1, 1)
arr.shape

(6, 1)

In [23]:
arr = arr.reshape(-1, 3)
arr.shape

(2, 3)

random array 생성

In [25]:
arr = np.random.randn(8, 8)
arr.shape

(8, 8)

In [26]:
arr = arr.reshape(32, 2)
arr.shape

(32, 2)

3차원으로 늘리기

In [28]:
arr = arr.reshape(-1, 2, 1)
arr.shape

(32, 2, 1)

In [29]:
arr = arr.reshape(-1, 2, 1, 1, 1, 1)
arr.shape

(32, 2, 1, 1, 1, 1)

## Ravel

In [30]:
arr.shape

(32, 2, 1, 1, 1, 1)

In [31]:
arr = arr.ravel()
arr.shape

(64,)

arr의 차원을 1로 바꿔줌  
나중에 배울 layer를 flatten 할 때 같은 기능이라 생각하면 됨 

arr.reshape(-1) 와 같음

In [32]:
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

In [33]:
arr.shape

(64,)

In [36]:
arr = np.expand_dims(arr, -1)
arr.shape

(1, 64, 1)

In [40]:
arr = arr.ravel()

In [41]:
arr.shape

(64,)

In [43]:
arr = np.expand_dims(np.expand_dims(arr, -1), 0)

In [44]:
arr.shape

(1, 64, 1)

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

np.zeros(), np.ones(), np.empty() 함수는 괄호 안에 쓴 숫자 개수만큼의 '0', '1', '비어있는 배열' 공간을 만들어줍니다.

np.zeros((2, 5)), np.ones((5, 3)), np.empty((4, 3)) 처럼 괄호 안에 tuple을 넣어주면 다차원 배열(multi-dimensional array)을 만들 수 있습니다.


In [115]:
np.zeros((2, 5))

TypeError: 'numpy.ndarray' object is not callable

In [114]:
z = np.zeros((2, 5))

TypeError: 'numpy.ndarray' object is not callable

In [73]:
z = np.zeros(1)
z

TypeError: 'numpy.ndarray' object is not callable

In [75]:
z1 = np.zeros(10)
z1

TypeError: 'numpy.ndarray' object is not callable

In [184]:
zeros = np.zeros([3, 3])
zeros

AttributeError: 'numpy.ndarray' object has no attribute 'zeros'

In [93]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [94]:
np.empty((4, 3))

array([[2.00000000e+000, 2.00000000e+000, 2.96439388e-323],
       [0.00000000e+000, 0.00000000e+000, 1.61590357e+184],
       [4.51616682e-090, 6.87005129e+169, 8.25998234e-072],
       [2.00500772e-076, 3.99910963e+252, 8.34405856e-309]])

In [99]:
f = np.arange(10)
f_2_5 = f.reshape(2, 5)

In [100]:
np.zeros_like(f_2_5)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [101]:
np.ones_like(f_2_5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [74]:
ones = np.ones([10])
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [80]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [122]:
ones * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [81]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

TypeError: 'numpy.ndarray' object is not callable

In [82]:
np.zeros(shape=(10,), dtype=np.int8)

TypeError: 'numpy.ndarray' object is not callable

In [83]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
np.empty(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [85]:
np.empty((3,5))

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [88]:
test_matrix = np.arange(30).reshape(5,6);
test_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

# np.zeros_like(), np.ones_like(), np.empty_like()

위 함수는 이미 있는 array와 동일한 모양과 데이터 형태를 유지한 상태에서 각 각 '0', '1', '빈 배열'을 반환합니다.


In [89]:
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [90]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [91]:
np.empty_like(test_matrix)

array([[4611686018427387904, 4611686018427387904,                  16,
                          0,                   0,                   0],
       [                  0,                   0,                   0,
                          0,                   0,                   0],
       [                  0,                   0,                   0,
        4189022123868451429, 4611686018427387904, 4611686018427387904],
       [                  8,                   0,                   0,
                          0,                   0,                   0],
       [                  0,                   0,                   0,
                          0,                   0,                   0]])

# np.arange()

np.arange() 는 Python의 range() 함수처럼 0부터 괄호안의 숫자 만큼의 정수 배열 값을 '배열'로 반환합니다. (returns not a list, but an array)  이 함수도 종종 사용하는 편이예요.


In [118]:
f = np.arange(10)
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# np.identity() 혹은 np.eye() 함수


np.identity() 혹은 np.eye() 함수를 사용하면 대각성분은 '1'이고 나머지 성분은 '0'으로 구성된 정방행렬인 항등행렬(identity matrix) 혹은 단위행렬(unit matrix)을 만들 수 있습니다.


In [120]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [121]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.asarray_chkfinite()

np.asarray_chkfinite() 함수를 쓰면 배열로 만들려고 하는 데이터 input에 결측값(NaN)이나 무한수(infinite number)가 들어있을 경우 'ValueError'를 반환하게 할 수 있습니다.  np.nan 으로 결측값을 넣어보고, np.inf 로 무한수를 추가해서 확인해보겠습니다.


In [103]:
e = [11, 12, 13, 14, 15]

In [105]:
np.asarray_chkfinite(e, dtype=float)


array([11., 12., 13., 14., 15.])

In [110]:
e_2 = [11, 12, 13, np.nan, 15] # with NaN


In [111]:
np.asarray_chkfinite(e_2, dtype=float)  # 에러 발생 

ValueError: array must not contain infs or NaNs

In [124]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [125]:
arr = np.arange(4, 9)
arr

array([4, 5, 6, 7, 8])

In [126]:
arr = np.arange(10, 20+1)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [127]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Index

In [128]:
nums = [1,2,3,4,5]

In [129]:
nums[2]

3

In [130]:
nums[2:]

[3, 4, 5]

In [131]:
arr[1]

array([3, 4, 5])

In [132]:
arr[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [133]:
arr[:4]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [134]:
nums = [1,2,3,4,[1,2,3]]
nums

[1, 2, 3, 4, [1, 2, 3]]

In [135]:
nums[4]

[1, 2, 3]

In [136]:
arr[1][2]

5

In [137]:
arr[1,2]

5

In [138]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [143]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

In [142]:
nums[2:4]

[3, 4]

## Boolean Indexing

In [145]:
data = np.random.randn(3,3)
data

array([[-0.17847908, -1.72293226,  0.23547019],
       [ 2.39021006,  0.30463476, -1.12965514],
       [-0.16044067,  0.46423194, -1.25375099]])

In [146]:
data <= 0

array([[ True,  True, False],
       [False, False,  True],
       [ True, False,  True]])

In [148]:
data[data <=0]

array([-0.17847908, -1.72293226, -1.12965514, -0.16044067, -1.25375099])

In [150]:
data[data <=0] = 1
data

array([[1.        , 1.        , 0.23547019],
       [2.39021006, 0.30463476, 1.        ],
       [1.        , 0.46423194, 1.        ]])

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [151]:
import numpy as np

In [152]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [153]:
arr +3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [154]:
arr *3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [155]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [156]:
arr + np.array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## Math Function

In [157]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [158]:
arr *5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [159]:
arr + arr 

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [160]:
np.add(arr, 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
arr + 1 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [162]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [164]:
arr = np.random.randint(2, size = 27).reshape(3, 3, 3)
arr_2 = np.random.randint(2, size = 9).reshape(3, 3)

In [165]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [166]:
arr + arr_2

array([[[1, 0, 0],
        [1, 1, 2],
        [1, 1, 1]],

       [[0, 1, 1],
        [2, 1, 1],
        [2, 0, 1]],

       [[0, 0, 0],
        [1, 1, 1],
        [2, 0, 1]]])

In [167]:
arr * arr_2

array([[[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [1, 0, 0]]])

In [168]:
np.sum(arr)

11

In [169]:
np.sum(arr + arr_2)

23

In [170]:
np.max(arr)

1

In [172]:
np.max(arr + arr_2)

2

In [173]:
np.min(arr * arr_2)

0

In [174]:
np.sum(arr + arr_2, axis = -1)

array([[1, 4, 3],
       [2, 4, 3],
       [0, 3, 3]])

In [175]:
np.mean(arr)

0.4074074074074074

In [182]:
arr2 = np.array([1, 6, 3, 7, 3, 2, 9])
arr2

AttributeError: 'numpy.ndarray' object has no attribute 'array'